### PR TITLE
Finish desktop-version of contact form

### PR DESCRIPTION
**Pull request by mhamedGd**
## THE DESKTOP VERSION WAS COMPLETED LAST WEEK IN SYNC WITH THE MOBILE VERSION SO YOU'LL ONLY SEE THE CHANGES IN THIS PULL REQUEST FOR THE CONTACT FORM WHICH NOW SUPPORTS DESKTOP MONITOR DIMENSIONS

##Completed
- Contact form desktop version :100:

### CODE REVIEW

**Review by awais-amjed — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️

Hi @mhamedGd , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

gif

## Required Changes ♻️

- [ ] Kindly note that your Desktop design does not match the Figma Design, instead the mobile design only expands to fit the screen. Kindly check the [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471) and **_"use media queries in your CSS file to make your desktop version look like the template you selected (Desktop: 768px or wider)"_** as mentioned in the [project Requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#project-requirements) 🤗
  - **_Kindly make changes in all sections of the webpage to make them look like the Desktop Version of the Figma Design and your project should be ready_** 🥳

_Your Design:_

image

_Figma Design:_

image

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by awais-amjed** [comment]
Hello @mhamedGd !

I've just realized that I have made a mistake in your review. I did not realize that my chrome was on 250% zoom and I couldn't see the desktop version of your Project.
I am sorry to mislead you. I haven't done that on purpose :blush:

I will review it again and get back to you! 😅

**Review by awais-amjed — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️

Hi @mhamedGd , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there! 🥳🎈✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] No Linter issues ✔️ 
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

gif

## Required Changes ♻️

- [ ] Kindly notice that the design of the first work in the works section (marked with a tick in the image) is not static. That is the design of a work card when the mouse hovers on it.
  - When you hover the mouse over a project, the design changes to say "Show Project", so that the user can see that project if they would like to.
  - So Kindly fix the design of works cards so that whenever a user hovers on one, they can see the button that says "Show Project"

_Your Design:_

image

_Figma Design:_

image

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ShahierNashaat — APPROVED** [review]
Hi @mhamedGd, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Good overall design ✔️
- Your code is clean and well documented ✔️

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
